"""
Schemas centralizados para a API SynapScale
"""

# ==================== AUTHENTICATION & USER SCHEMAS ====================
from .auth import (
    UserLogin,
    UserRegister,
    UserResponse,
    TokenResponse,
    RefreshTokenRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    PasswordChangeRequest,
    EmailVerificationRequest,
    TwoFactorSetup,
    TwoFactorVerify,
    TwoFactorDisable,
    UserPreferences,
    UserProfile,
    UserUpdate,
    UserStats,
    SessionInfo,
    AuthProvider,
)

# ==================== WORKFLOW SCHEMAS ====================
from .workflow import (
    WorkflowBase,
    WorkflowCreate,
    WorkflowUpdate,
    WorkflowResponse,
    WorkflowExecutionResponse,
    WorkflowSearch,
    WorkflowStats,
    WorkflowVersion,
    WorkflowTemplate,
    WorkflowTemplateResponse,
    NodeBase,
    NodeCreate,
    NodeUpdate,
    NodeResponse,
    ConnectionBase,
    ConnectionCreate,
    ConnectionUpdate,
    ConnectionResponse,
    ExecutionLogResponse,
    WorkflowExecutionCreate,
    WorkflowExecutionUpdate,
    WorkflowMetrics,
    WorkflowAnalytics,
)

# ==================== WORKSPACE SCHEMAS ====================
from .workspace import (
    WorkspaceBase,
    WorkspaceCreate,
    WorkspaceUpdate,
    WorkspaceResponse,
    MemberInvite,
    MemberResponse,
    MemberUpdate,
    InvitationResponse,
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    CollaboratorPermissions,
    CollaboratorAdd,
    CollaboratorResponse,
    CommentBase,
    CommentCreate,
    CommentUpdate,
    CommentResponse,
    ActivityResponse,
    ProjectVersionResponse,
    VersionCreate,
    WorkspaceStats,
    WorkspaceSearch,
    ProjectSearch,
    BulkMemberOperation,
    BulkProjectOperation,
    # Note: Workspace has its own BulkOperationResponse - imported with qualified name
    RealTimeEvent,
    CursorPosition,
    EditOperation,
    NotificationSettings,
    NotificationPreferences,
    WorkspaceIntegration,
    IntegrationResponse,
)

# Import workspace BulkOperationResponse with alias to avoid conflicts
from .workspace import BulkOperationResponse as WorkspaceBulkOperationResponse

# ==================== MARKETPLACE SCHEMAS ====================
from .marketplace import (
    ComponentType,
    ComponentCategory,
    ComponentStatus,
    LicenseType,
    ComponentBase,
    ComponentCreate,
    ComponentUpdate,
    ComponentResponse,
    ComponentSearch,
    ComponentSearchResponse,
    RatingBase,
    RatingCreate,
    RatingResponse,
    RatingStats,
    DownloadResponse,
    PurchaseCreate,
    PurchaseResponse,
    ComponentVersionResponse,
    MarketplaceStats,
    BulkComponentOperation,
    # Note: Marketplace has its own BulkOperationResponse - imported with qualified name
    ComponentModerationResponse,
    ModerationAction,
)

# Import marketplace BulkOperationResponse with alias to avoid conflicts
from .marketplace import BulkOperationResponse as MarketplaceBulkOperationResponse

# ==================== STANDARDIZED RESPONSE SCHEMAS ====================
from .response import (
    BaseResponse,
    DataResponse,
    ListResponse,
    PaginatedListResponse,
    EmptyResponse,
    GenericBulkOperationResponse,
    MetadataResponse,
    HealthCheckResponse,
    PaginationMeta,
    # Helper functions
    create_data_response,
    create_list_response,
    create_empty_response,
    create_pagination_meta,
)

# ==================== ERROR HANDLING SCHEMAS ====================
from .error import (
    ErrorDetail,
    ErrorResponse,
    ValidationErrorResponse,
    AuthenticationErrorResponse,
    AuthorizationErrorResponse,
    NotFoundErrorResponse,
    ConflictErrorResponse,
    RateLimitErrorResponse,
    InternalServerErrorResponse,
    BadGatewayErrorResponse,
)

# ==================== EXPORTS ====================
__all__ = [
    # Authentication & User
    "UserLogin",
    "UserRegister", 
    "UserResponse",
    "TokenResponse",
    "RefreshTokenRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "PasswordChangeRequest",
    "EmailVerificationRequest",
    "TwoFactorSetup",
    "TwoFactorVerify",
    "TwoFactorDisable",
    "UserPreferences",
    "UserProfile",
    "UserUpdate",
    "UserStats",
    "SessionInfo",
    "AuthProvider",
    
    # Workflow
    "WorkflowBase",
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowExecutionResponse",
    "WorkflowSearch",
    "WorkflowStats",
    "WorkflowVersion",
    "WorkflowTemplate",
    "WorkflowTemplateResponse",
    "NodeBase",
    "NodeCreate",
    "NodeUpdate",
    "NodeResponse",
    "ConnectionBase",
    "ConnectionCreate",
    "ConnectionUpdate",
    "ConnectionResponse",
    "ExecutionLogResponse",
    "WorkflowExecutionCreate",
    "WorkflowExecutionUpdate",
    "WorkflowMetrics",
    "WorkflowAnalytics",
    
    # Workspace
    "WorkspaceBase",
    "WorkspaceCreate",
    "WorkspaceUpdate",
    "WorkspaceResponse",
    "MemberInvite",
    "MemberResponse",
    "MemberUpdate",
    "InvitationResponse",
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "CollaboratorPermissions",
    "CollaboratorAdd",
    "CollaboratorResponse",
    "CommentBase",
    "CommentCreate",
    "CommentUpdate",
    "CommentResponse",
    "ActivityResponse",
    "ProjectVersionResponse",
    "VersionCreate",
    "WorkspaceStats",
    "WorkspaceSearch",
    "ProjectSearch",
    "BulkMemberOperation",
    "BulkProjectOperation",
    "WorkspaceBulkOperationResponse",  # Aliased to avoid conflicts
    "RealTimeEvent",
    "CursorPosition",
    "EditOperation",
    "NotificationSettings",
    "NotificationPreferences",
    "WorkspaceIntegration",
    "IntegrationResponse",
    
    # Marketplace
    "ComponentType",
    "ComponentCategory",
    "ComponentStatus",
    "LicenseType",
    "ComponentBase",
    "ComponentCreate",
    "ComponentUpdate",
    "ComponentResponse",
    "ComponentSearch",
    "ComponentSearchResponse",
    "RatingBase",
    "RatingCreate",
    "RatingResponse",
    "RatingStats",
    "DownloadResponse",
    "PurchaseCreate",
    "PurchaseResponse",
    "ComponentVersionResponse",
    "MarketplaceStats",
    "BulkComponentOperation",
    "MarketplaceBulkOperationResponse",  # Aliased to avoid conflicts
    "ComponentModerationResponse",
    "ModerationAction",
    
    # Standardized Responses
    "BaseResponse",
    "DataResponse",
    "ListResponse",
    "PaginatedListResponse",
    "EmptyResponse",
    "GenericBulkOperationResponse",
    "MetadataResponse",
    "HealthCheckResponse",
    "PaginationMeta",
    "create_data_response",
    "create_list_response",
    "create_empty_response",
    "create_pagination_meta",
    
    # Error Handling
    "ErrorDetail",
    "ErrorResponse",
    "ValidationErrorResponse",
    "AuthenticationErrorResponse",
    "AuthorizationErrorResponse",
    "NotFoundErrorResponse",
    "ConflictErrorResponse",
    "RateLimitErrorResponse",
    "InternalServerErrorResponse",
    "BadGatewayErrorResponse",
]
